### ISSUE TITLE
Driver name

### ISSUE THREAD

**Issue by commarmi76** [SDRplay/SoapySDRPlay#4]
I'm using SoapySDRPlay with "API/HW DRIVER – V3" and gr-soapy inside Gnu Radio.
During the proces I noticed the driver name in your code is "sdrPlay" instead of "sdrplay". In fact opened an issue at SoapySDRPlay: https://gitlab.com/librespacefoundation/gr-soapy/-/issues/84

But, I'm wondering if the driver name change it was deliberated or not.
I guess if you change the driver name some softwares (cubicsdr, gqrx, etc..) could stop working.

**Comment by fventuri** [comment]
Thanks for catching that error, @commarmi76 

I just changed the name of the driver to 'sdrplay' (all lowercase), as it should have been.
I think we ran all of the initial tests using CubicSDR, and CubicSDR doesn't seem to have a preference about the driver name (I just ran a couple of tests in CubiSDR with the all lowercase driver name, and it worked without any problem).

Since you are running it in a different way that we initially did, you may see other issues we haven't encountered; please let me know,  and I'll be happy to look into them.

Franco
